# src/main/resources/application.yml
server:
  port: 8080

spring:
  datasource:
    # ???? MySQL ???????? blog ??????
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 925115
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update           # ??????/????????????? none / validate?
    show-sql: false

  mail:
    host: smtp.qq.com
    port: 465
    username: 2945706262@qq.com
    password: yplgrzlnexubddad
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: admin123456
  bucket: blog

logging:
  level:
    root: INFO
    org.lxly.blog: DEBUG
