# src/main/resources/application.yml
server:
  port: 8080

spring:
  datasource:
    # ???? MySQL ???????? blog ??????
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 925115
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update           # ??????/????????????? none / validate?
    show-sql: false

  mail:
    host: localhost
    port: 1025                     # ??? MailHog / FakeSMTP ??
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: admin123456
  bucket: blog

logging:
  level:
    root: INFO
    org.lxly.blog: DEBUG
